version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y update
            sudo apt-get -y install python-dev
            sudo apt-get -y install python-pip
            sudo pip install awscli --upgrade --user

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm run lint

    #   - deploy:
    #       name: Deploy
    #       command: |
    #         if [ "${CIRCLE_BRANCH}" == "master" ]; then
    #           ./scripts/deploy.sh
    #         else
    #           echo "Not deploying this branch"
    #         fi
